name: prophet_profiler
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  
  # HTTP Client
  dio: ^5.7.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  
  # UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  fl_chart: ^0.69.0
  
  # Utils
  equatable: ^2.0.5
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/